# Change these first
owner: clye-gmbh # Your GitHub organization or username, where this repository lives
repo: uptime # The name of this repository

sites:
  - name: Clye.app
    url: https://clye.app
  - name: Bot
    url: https://bot.clye.app
  - name: Homepage
    url: https://clye-gmbh.de
  - name: AI-Hub
    url: https://ai.clye-gmbh.de
  - name: AI-Hub Kaiser
    url: https://ai-hub.kaiser.bluetomato.tech
  - name: Realite
    url: https://realite.app

status-website:
  baseUrl: /uptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Clye Uptime
  introTitle: "Hier ist die uptime un der aktuelle Status der CLYE Produkte zu sehen"
  introMessage: "Alle störungen sind hier aufgelistet"
  navbar:
    - title: Status
      href: /$REPO
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
assignees:
  - enex

i18n:
  activeIncidents: Aktive Störungen
  allSystemsOperational: Alle Systems sind bereit
  incidentReport: "Incident #$NUMBER report →"
  activeIncidentSummary: Opened at $DATE with $POSTS posts
  incidentTitle: Incident $NUMBER Details
  incidentDetails: Incident Details
  incidentFixed: Fixed
  incidentOngoing: Ongoing
  incidentOpenedAt: Opened at
  incidentClosedAt: Closed at
  incidentViewOnGitHub: View and Subscribe on GitHub
  incidentCommentSummary: Posted at $DATE by $AUTHOR
  incidentBack: ← Back to all incidents
  pastIncidents: Past Incidents
  pastIncidentsResolved: Resolved in $MINUTES minutes with $POSTS posts
  liveStatus: Live Status
  overallUptime: "Overall uptime: $UPTIME"
  overallUptimeTitle: Overall uptime
  averageResponseTime: "Average response time: $TIMEms"
  averageResponseTimeTitle: Average response
  sevelDayResponseTime: 7-day response time
  responseTimeMs: Response time (ms)
  up: Up
  down: Down
  degraded: Degraded
  ms: ms
  loading: Loading
  navGitHub: GitHub
  footer: This page is [open source]($REPO), powered by [Upptime](https://upptime.js.org)
  rateLimitExceededTitle: Rate limit exceeded
  rateLimitExceededIntro: You have exceeded the number of requests you can do in an hour, so you'll have to wait before accessing this website again. Alternately, you can add a GitHub Personal Access Token to continue to use this website.
  rateLimitExceededWhatDoesErrorMean: What does this error mean?
  rateLimitExceededErrorMeaning: This website uses the GitHub API to access real-time data about our websites' status. By default, GitHub allows each IP address 60 requests per hour, which you have consumed.
  rateLimitExceededErrorHowCanFix: How can I fix it?
  rateLimitExceededErrorFix: You can wait for another hour and your IP address' limit will be restored. Alternately, you can add your GitHub Personal Access Token, which gives you an additional 5,000 requests per hour.
  rateLimitExceededGeneratePAT: Learn how to generate a Personal Access Token
  rateLimitExceededHasSet: You have a personal access token set.
  rateLimitExceededRemoveToken: Remove token
  rateLimitExceededGitHubPAT: GitHub Personal Access Token
  rateLimitExceededCopyPastePAT: Copy and paste your token
  rateLimitExceededSaveToken: Save token
  errorTitle: An error occurred
  errorIntro: An error occurred in trying to get the latest status details.
  errorText: You can try again in a few moments.
  errorHome: Go to the homepage
  pastScheduledMaintenance: Past Scheduled Maintenance
  scheduledMaintenance: Scheduled Maintenance
  scheduledMaintenanceSummaryStarted: Started at $DATE for $DURATION minutes
  scheduledMaintenanceSummaryStarts: Starts at $DATE for $DURATION minutes
  startedAt: Started at
  startsAt: Starts at
  duration: Duration
  durationMin: $DURATION minutes
  incidentCompleted: Completed
  incidentScheduled: Scheduled
  duration24H: 24h
  duration7D: 7d
  duration30D: 30d
  duration1Y: 1y
  durationAll: Alle
  locale: de-DE
